export interface IRole {
  ADMIN: "ADMIN";
  ASSISTANT: "ASSISTANT";
  SALES_TECHNICIAN: "SALES_TECHNICIAN";
  SALES_SPECIALIST: "SALES_SPECIALIST";
  PROJECT_DESIGNER: "PROJECT_DESIGNER";
  COLLABORATOR: "COLLABORATOR";
  INSTALLER: "INSTALLER";
  TECHNICIAN: "TECHNICIAN";
  CUSTOMER: "CUSTOMER";
}
